export const defaultColKey = [
    'ID',
    'Title',
    'Artist',
    'Status',
    'Key',
    'My Key',
    'Tempo',
    'Duration',
    'Time Signature',
    'Language',
    'Listen',
    'Composers',
    'Songwriters',
    'Arrangers',
    'Genres',
    'Moods',
    'Tags',
];
